name: TMSW-Additions
version: 1.2
main: de.powerspieler.tmswadditions.TMSWAdditions
api-version: 1.19

commands:
  death:
    description: Get last point of death
  map:
    description: Convert MapIDs to get pictures
  playerhead:
    description: Set texture of craftable playerheads
  key:
    description: Add a hidden lore to any item to make them unique

