name: TMSW-Additions
version: '${project.version}'
main: de.powerspieler.tmswadditions.TMSWAdditions
api-version: '1.20'

commands:
  death:
    description: Get last point of death
  map:
    description: Convert MapIDs to get pictures
  playerhead:
    description: Set texture of craftable playerheads
  key:
    description: Add a hidden lore to any item to make them unique

  test:
    description: testing things

